In [2]:
import numpy as np
import time

In [3]:
#arr = np.array([1,2,3,4,5])
#print(arr, type(arr), arr.shape)

#arr2 = np.array([1,2,3,4,5,"prime"])
#print(arr2, type(arr2), arr2.shape)

#arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
#print(arr2d, type(arr2d), arr2d.shape)

In [4]:
#execution performance
size = 1_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#numps array
#np_arr = np.array(py_list)
#start = time.time()
#sq_array = np_arr ** 2
#end = time.time()
#print(f"numpy array time = {end-start} seconds")

python list time = 0.1351025104522705 seconds


In [5]:
arr1 = np.zeros((3,4), dtype = "int64") #prefill
print(arr1, arr1.shape)

arr2 = np.full((3,4), 100) #prefill with val
print(arr2)

arr3 = np.eye(3) #identity matrix
print(arr3, arr3.shape)

arr4 = np.arange(1,11,1) #range(start,end,step)
print(arr4, arr4.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] (3, 4)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  2  3  4  5  6  7  8  9 10] (10,)


In [6]:
#properties
#arr = np.array([1,23,4,5])
#print(arr)
print(arr.shape) #dimension m*n
print(arr.size) #size of an array
print(arr.dtype) #datatype of an array
print(arr.ndim) #dimention of an array

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

NameError: name 'arr' is not defined

In [7]:
#operations on array
#arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattend = arr.flatten()
print(flattend, flattend.shape)

NameError: name 'arr' is not defined

In [8]:
#indexing
#arr = np.array([1,2,3,4,5])
#arr = np.array([[1,2,3], [4,5,6]])
#print(arr[0][1])
#print(arr[0])
#print(arr[1])

#fancy indexing
#arr = np.array([1,2,3,4,5])
#indx = [0,1,3]
#print(arr[indx])

#Boolean indexing
#arr = np.array([1,2,3,4,5])
print(arr[arr>2])
print(arr[arr%2==0])

NameError: name 'arr' is not defined

In [9]:
#slicing
#arr = np.array([1,2,3,4,5])
print(arr[1:4]) #[start, end, step]
print(arr[::2])

NameError: name 'arr' is not defined

In [10]:
#copy vs view
#nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)

sub_list[0] = 200
print(sub_list)
print(nums)


#arr = np.array([1,2,3,4,5])
#sub_arr = arr[1:3]
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr[0] = 200
print(sub_arr)
print(arr)

NameError: name 'nums' is not defined

In [20]:
import numpy as np
import time

In [21]:
#datatypes
#arr = np.array([1,2,3,4,5])
#print(arr, arr.dtype)

#arr1 = np.array([3+4j])
#arr2 = np.array([5+6j])
#print(arr1 + arr2)


In [27]:
#multidimensional
#arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D)

sum = np.sum(arr2D)
print(sum)

sum_row = np.sum(arr2D, axis=0)
print(sum_row)

sum_col = np.sum(arr2D, axis=1)
print(sum_col)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [37]:
#3D array
#arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])    #2*3*2
print(arr3D, arr3D.shape)

#indexing
print(arr3D[1,1,0])

#slicing
print(arr3D[:,0,:])   #first row from both array

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]


In [41]:
#Vectorization and Broadcasting
#vectorization
#arr1 = np.array([12,3,4,5])
print(arr1**2)
print(arr1+5)

#Broadcasting -> scaling
#arr1 = np.array([12,4,5,7])
arr2 = np.array([[23,4,5,5],[4,7,5,8]])
print(arr1+arr2)

[144   9  16  25]
[17  8  9 10]
[[35  8 10 12]
 [16 11 10 15]]


In [42]:
#normalization
#arr = np.array([[1,2], [3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [60]:
#mathematical function
#arr = np.array([1,2,3,4,5])

#aggregation
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.var(arr))
print(np.argmin(arr))
print(np.mean(arr))
print(np.argmax(arr))

#power function
print(np.square(arr))
print(np.sqrt(arr))

#log
print(np.log(arr))
print(np.log2(arr))

#rounding
print(np.floor(5.89))
print(np.ceil(5.89))

print(np.sort(arr))
print(np.abs(arr))

15
120
1
5
2.0
0
3.0
4
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
5.0
6.0
[1 2 3 4 5]
[1 2 3 4 5]
