In [2]:
import numpy as np
import time

In [3]:
#arr = np.array([1,2,3,4,5])
#print(arr, type(arr), arr.shape)

#arr2 = np.array([1,2,3,4,5,"prime"])
#print(arr2, type(arr2), arr2.shape)

#arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
#print(arr2d, type(arr2d), arr2d.shape)

In [4]:
#execution performance
size = 1_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#numps array
#np_arr = np.array(py_list)
#start = time.time()
#sq_array = np_arr ** 2
#end = time.time()
#print(f"numpy array time = {end-start} seconds")

python list time = 0.15423321723937988 seconds


In [5]:
arr1 = np.zeros((3,4), dtype = "int64") #prefill
print(arr1, arr1.shape)

arr2 = np.full((3,4), 100) #prefill with val
print(arr2)

arr3 = np.eye(3) #identity matrix
print(arr3, arr3.shape)

arr4 = np.arange(1,11,1) #range(start,end,step)
print(arr4, arr4.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] (3, 4)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  2  3  4  5  6  7  8  9 10] (10,)


In [13]:
#properties
arr = np.array([1,23,4,5])
print(arr)
print(arr.shape) #dimension m*n
print(arr.size) #size of an array
print(arr.dtype) #datatype of an array
print(arr.ndim) #dimention of an array

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[ 1 23  4  5]
(4,)
4
int64
1
[ 1. 23.  4.  5.] float64
